### PR TITLE
Fix RowDescription so that query containing multibyte column names to work

### PR DESCRIPTION
**Pull request by sonots**
Fix https://github.com/wvanbergen/vertica/issues/64

### CODE REVIEW

**Comment by sonots** [comment]
tests failed, but it looks it is not related with this PR

**Comment by wvanbergen** [comment]
I'm working on getting CI working again. Could you add a test that makes sure this doesn't break again?

**Comment by wvanbergen** [comment]
CI should be fixed now - can you rebase on the latest master?

**Comment by sonots** [comment]
Added tests

**Comment by wvanbergen** [comment]
Awesome, thanks!

**Pull request merged**
